part of 'balance_sheet_bloc.dart';

@freezed
class BalanceSheetBlocState with _$BalanceSheetBlocState {
  const factory BalanceSheetBlocState({
    required List<MyBalanceSheetResponse> bankDepActual,
    required List<MyBalanceSheetResponse> bankLoanActual,
    required List<MyBalanceSheetResponse> segmentBankWide,
    required List<MyBalanceSheetResponse> bankWideDepAvg,
    required List<MyBalanceSheetResponse> bankWideLoanAvg,
    required List<MyBalanceSheetResponse> avgSegmentBankWide,
    required List<MyBalanceSheetTypeResponse> regionActual,
    required List<MyBalanceSheetTypeResponse> areaActual,
    required List<MyBalanceSheetTypeResponse> branchActual,
    required List<MyBalanceSheetTypeResponse> regionAvg,
    required List<MyBalanceSheetTypeResponse> areaAvg,
    required List<MyBalanceSheetTypeResponse> branchAvg,
    required List<MyBalanceSheetRmResponse> rmData,
    required List<MyBalanceSheetRmResponse> actualSegmentRegion,
    required List<MyBalanceSheetRmResponse> actualSegmentArea,
    required List<MyBalanceSheetRmResponse> actualSegmentBranch,
    required List<MyBalanceSheetRmResponse> avgSegmentRegion,
    required List<MyBalanceSheetRmResponse> avgSegmentArea,
    required List<MyBalanceSheetRmResponse> avgSegmentBranch,
    List<String>? regionList,
    List<String>? branchByArea,
    List<String>? rmByBranch,
    List<String>? areaByRegion,
    String? selectedDate,
    String? regionItem,
    String? areaItem,
    String? branchItem,
    String? rmItem,
    String? selectedStartDate,
    DateTime? pickedDate,
    DateTime? twoDaysAgoSelectedDate,
    DateTime? yesterdayDate,
    DateTime? twoDaysAgo,
    String? previousDate,
    String? previousSelectedDate,
    DateTime? selectedLastDayOfLastMonth,
    DateTime? lastDayOfLastMonth,
    String? selectedLastDayOfLastMonthString,
    String? lastDayOfLastMonthString,
    String? yesterdayDateString,
    String? yesterDayDateString,
    String? regionType,
    String? segmentType,
    String? areaType,
    String? branchType,
    String? rmType,
  }) = _BalanceSheetState;

  factory BalanceSheetBlocState.initial() => BalanceSheetBlocState(
        bankDepActual: [],
        bankLoanActual: [],
        segmentBankWide: [],
        bankWideDepAvg: [],
        bankWideLoanAvg: [],
        avgSegmentBankWide: [],
        regionActual: [],
        areaActual: [],
        branchActual: [],
        regionAvg: [],
        areaAvg: [],
        branchAvg: [],
        rmData: [],
        actualSegmentRegion: [],
        actualSegmentArea: [],
        actualSegmentBranch: [],
        avgSegmentRegion: [],
        avgSegmentArea: [],
        avgSegmentBranch: [],
      );
}
